[package]
name = "evolved-creatures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/*",
]

[dependencies]
soft-body-engine = { path = "crates/soft-body-engine" }

bevy = "0.12.0"
bevy-inspector-egui = "0.21.0"
bevy_egui = "0.23.0"
bevy_screen_diagnostics = "0.4"