[package]
name = "random-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "2.0.52"
quote = "1.0.35"
proc-macro2 = "1.0.79"
rand = "0.8.5"
